const express = require('express');
const router = express.Router();
const aiRateLimiter = require('../middleware/rateLimiter');

// POST /api/ai/generate-description (Protected by rate limiter)
router.post('/generate-description', aiRateLimiter, async (req, res) => {
  const { title } = req.body;

  if (!title || typeof title !== 'string' || title.trim().length < 3) {
    return res.status(400).json({
      success: false,
      error: 'Please provide a valid task title of at least 3 characters'
    });
  }

  const cleanTitle = title.trim();
  const apiKey = process.env.GEMINI_API_KEY;

  // 1. If API Key is provided, attempt live Gemini API call
  if (apiKey && apiKey !== 'your_gemini_api_key_here') {
    try {
      const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`;
      const prompt = `You are a software project manager. Given the task title: "${cleanTitle}", generate a JSON object with:
1. "description": A concise, actionable, professional 2-3 sentence task description.
2. "suggestedPriority": either "low", "medium", or "high".
3. "estimatedHours": reasonable integer hours to complete.
Respond ONLY with raw JSON in this format: {"description": "...", "suggestedPriority": "...", "estimatedHours": 4}`;

      const response = await fetch(endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }]
        })
      });

      if (response.ok) {
        const data = await response.json();
        const candidateText = data.candidates?.[0]?.content?.parts?.[0]?.text || '';
        const cleanedJson = candidateText.replace(/```json/g, '').replace(/```/g, '').trim();
        const parsed = JSON.parse(cleanedJson);

        return res.status(200).json({
          success: true,
          aiProvider: 'Google Gemini 1.5 Flash',
          taskTitle: cleanTitle,
          description: parsed.description,
          suggestedPriority: parsed.suggestedPriority || 'medium',
          estimatedHours: parsed.estimatedHours || 4,
          disclaimer: 'Generated by Gemini AI. Please review and adjust before saving.'
        });
      }
    } catch (err) {
      console.warn('[AI API Warning] External AI call failed, engaging graceful degradation fallback:', err.message);
    }
  }

  // 2. Graceful Degradation Fallback (Core Requirement)
  // Guarantees zero application crashes and instant feedback even when offline / unkeyed
  let suggestedPriority = 'medium';
  let hours = 3;

  const lower = cleanTitle.toLowerCase();
  if (lower.includes('docker') || lower.includes('security') || lower.includes('auth') || lower.includes('jwt') || lower.includes('bug')) {
    suggestedPriority = 'high';
    hours = 6;
  } else if (lower.includes('docs') || lower.includes('readme') || lower.includes('style') || lower.includes('color')) {
    suggestedPriority = 'low';
    hours = 2;
  }

  const generatedDescription = `Implement and test "${cleanTitle}" in accordance with project development guidelines. Verify component lifecycle, enforce boundary validation, and write automated verification assertions.`;

  return res.status(200).json({
    success: true,
    aiProvider: 'AWDF AI Engine (Graceful Degradation Fallback)',
    taskTitle: cleanTitle,
    description: generatedDescription,
    suggestedPriority,
    estimatedHours: hours,
    disclaimer: 'Generated by AI Assistant. Please review and adjust before saving.'
  });
});

module.exports = router;
